name: pneumonia_detection
description: A web app for pneumonia detection using x-ray and ct-san

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  build_runner: ^2.1.8
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_gen: ^4.1.6
  flutter_gen_runner: ^4.1.6
  flutter_modular: ^4.5.0
  image_picker_web: ^2.1.1
  responsive_framework: ^0.1.7
  tflite: ^1.1.2
  tflite_flutter: ^0.9.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/model/model.tflite
    - assets/model/labels.txt
  fonts:
    - family: hebrew
      fonts:
        - asset: assets/fonts/OpenSansHebrew-Regular.ttf
        - asset: assets/fonts/OpenSansHebrew-Bold.ttf
          weight: 700
flutter_gen:
  output: lib/gen
  # Optional
  integrations:
    flutter_svg: true
